---
- name: systemctl restart ssh
  become: true
  ansible.builtin.systemd:
    name: "{{ sshd__service }}"
    state: restarted
  when: sshd__service is defined and ansible_service_mgr == 'systemd'

- name: service restart ssh
  become: true
  ansible.builtin.service:
    name: "{{ sshd__service }}"
    state: restarted
  when: sshd__service is defined and ansible_service_mgr != 'systemd'
